### ISSUE TITLE
Mistake in readme

### ISSUE THREAD

**Issue by locktarr** [mkabilov/pg2ch#25]
There is a little mistake in readme guide. In the description of the configuration file there is 'pg' key for the postgres connection and etc. This error follows:

root@9529452bd859:/home/go/pg2ch# go run main.go --config config.yaml
could not load config: publication name is not specified
exit status 1

If you look in the source file (pkg\config\config.go) there is different key 'postgres'
And if replace 'pg' with 'postgres', it works correctly.

**Comment by mkabilov** [comment]
fixed.
thank you!
